project	= SYSTEM
output	= $(project).DLL
link	= $(project).LNK
sources	= system.cpp list.cpp services.cpp services\foo.cpp
objects	= system.obj list.obj services.obj foo.obj
options	= /c /fe=$(output) /s /ox /l=div_dll

$(output):
	wcl386 $(options) $(sources)
	# TODO: Remove /c option when DIV.H warning 1027 is solved to perform all compilation and linking in one step using wcl386 command.
	# Then, the following wlink code will been not necessary anymore.
	%write	$(link) NAME $@
	%write	$(link) SYSTEM DIV_DLL
	%write	$(link) FILE {$(objects)}
	wlink	@$(link) disable 1027

clean:		.SYMBOLIC
	@echo cleaning directory
	@if exist *.obj @del *.obj
	@if exist *.lnk @del *.lnk
	@if exist *.err @del *.err