/* ----------------------------------------------------------------------------
 * SYSTEM.DLL - System library for DIV Games Studio.
 * (C) VisualStudioEX3, José Miguel Sánchez Fernández - 2022
 * DIV Games Studio 2 (C) Hammer Technologies - 1998, 1999
 * ---------------------------------------------------------------------------- */

#include "SYSTEM.H"

void __export divlibrary(LIBRARY_PARAMS)
{
}

void __export divmain(COMMON_PARAMS)
{
    GLOBAL_IMPORT();    
}

void __export divend(COMMON_PARAMS)
{
}
