//! SYSTEM.DLL - System library for DIV Games Studio 2.
//! @copyright TLSA98 Engine (C) VisualStudioEX3, José Miguel Sánchez Fernández - 2022
//! @copyright DIV Games Studio 2 (C) Hammer Technologies, Daniel Navarro Medrano - 1998, 1999
/*!
    Main engine file and access to all core services.
*/

#ifndef __SYSTEM_DLL_
#define __SYSTEM_DLL_

#include "SYSTEM\DIV2.H"        // DIV Games Studio 2 header setup and extensions.
#include "SYSTEM\GLOBAL.H"      // Global members.
#include "SYSTEM\BOOL.H"        // Boolean type and constants.
#include "SYSTEM\SERVICES.H"    // Service provider.
#include "SYSTEM\MEM.H"         // Memory service.
#include "SYSTEM\STRING.H"      // String service.
#include "SYSTEM\DIVFNEXP.H"    // DIV Games Studio function exporter service.
#include "SYSTEM\MATH.H"        // Math service.

#endif