# FOO.DLL - Test library.
# @copyright TLSA98 Engine (C) VisualStudioEX3, José Miguel Sánchez Fernández - 2022, 2023
# @copyright DIV Games Studio 2 (C) Hammer Technologies, Daniel Navarro Medrano - 1998, 1999
#
#  	Makefile.
#

sources	= foo.cpp

all: compile clean

compile: 	.SYMBOLIC
	$(COMPILER_CMD) $(sources)

clean: 		.SYMBOLIC
	@echo cleaning directory
	@if exist *.obj @del /f /q *.obj
	@if exist *.lnk @del /f /q *.lnk
	@if exist *.err @del /f /q *.err